"""empty message

Revision ID: 28501e1770bb
Revises: da5cd4c2fab8
Create Date: 2023-09-15 00:34:39.953992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28501e1770bb'
down_revision = 'da5cd4c2fab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=25), nullable=False))
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=False))
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('length', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_atmosphering_speed', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('crew', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('passengers', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('starship_class', sa.String(length=100), nullable=False))
        batch_op.drop_column('atmosphere')
        batch_op.drop_column('population')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('atmosphere', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('starship_class')
        batch_op.drop_column('passengers')
        batch_op.drop_column('crew')
        batch_op.drop_column('max_atmosphering_speed')
        batch_op.drop_column('length')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('model')
        batch_op.drop_column('name')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('gravity',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('diameter')
        batch_op.drop_column('rotation_period')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('hair_color',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.drop_column('skin_color')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
