"""empty message

Revision ID: b844e866fdcb
Revises: 
Create Date: 2023-09-15 20:31:08.605856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b844e866fdcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('favorite_planets')
        batch_op.drop_column('favorite_starships')
        batch_op.drop_column('favorite_characters')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_characters', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favorite_starships', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favorite_planets', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
