"""empty message

Revision ID: da5cd4c2fab8
Revises: f177a87fd584
Create Date: 2023-09-14 23:40:38.778966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5cd4c2fab8'
down_revision = 'f177a87fd584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=True),
    sa.Column('atmosphere', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_table_people',
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('favorites_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], )
    )
    op.create_table('join_table_planets',
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.Column('favorites_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], )
    )
    op.create_table('join_table_starships',
    sa.Column('starships_id', sa.Integer(), nullable=True),
    sa.Column('favorites_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['starships_id'], ['starships.id'], )
    )
    op.drop_table('startships')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_starships', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('favorite_startships')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starships', sa.String(length=15), nullable=False))
        batch_op.drop_column('startships')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startships', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.drop_column('starships')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_startships', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('favorite_starships')

    op.create_table('startships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('population', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('atmosphere', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='startships_pkey')
    )
    op.drop_table('join_table_starships')
    op.drop_table('join_table_planets')
    op.drop_table('join_table_people')
    op.drop_table('starships')
    # ### end Alembic commands ###
