"""empty message

Revision ID: f177a87fd584
Revises: b559aff0bf3a
Create Date: 2023-09-14 23:15:55.729549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f177a87fd584'
down_revision = 'b559aff0bf3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorite_characters', sa.String(length=200), nullable=True),
    sa.Column('favorite_planets', sa.String(length=200), nullable=True),
    sa.Column('favorite_startships', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('birth_year', sa.String(length=15), nullable=False),
    sa.Column('eye_color', sa.String(length=15), nullable=False),
    sa.Column('gender', sa.String(length=25), nullable=False),
    sa.Column('hair_color', sa.String(length=15), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('startships', sa.String(length=15), nullable=False),
    sa.Column('home_world', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('terrain', sa.String(length=30), nullable=False),
    sa.Column('gravity', sa.String(length=3), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=True),
    sa.Column('climate', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=True),
    sa.Column('atmosphere', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('startships')
    op.drop_table('planets')
    op.drop_table('people')
    op.drop_table('favorites')
    # ### end Alembic commands ###
